import { execSync } from "child_process";
import {
  existsSync,
  mkdirSync,
  writeFileSync,
  readFileSync,
  readdirSync,
  copyFileSync,
  rmSync,
  statSync,
} from "fs";
import { join, dirname, relative } from "path";
import { parse as parseToml, stringify as stringifyToml } from "smol-toml";
import type {
  AgentAdapter,
  AgentSessionConfig,
  StartCommand,
  ResolvedArtifacts,
  RootEntry,
  McpServerEntry,
  PluginEntry,
  PrepareSessionOptions,
  PreparedSession,
  CleanSessionOptions,
  CleanSessionResult,
  LocalArtifacts,
  QualifiedId,
} from "@pulsemcp/air-core";
import {
  buildManifest,
  deleteManifest,
  diffManifest,
  getManifestPath,
  loadManifest,
  manifestMcpServersAreAirOwned,
  manifestSkillsAreAirOwned,
  writeManifest,
  parseQualifiedId,
  resolveReference,
} from "@pulsemcp/air-core";
import { scanLocalSkills } from "./scan-local-skills.js";
import {
  previousSkillOwnership,
  relinquishedSkillMessage,
  unverifiedSkillsMessage,
} from "./skill-ownership.js";
import {
  hasMcpServer,
  previousMcpServerOwnership,
  relinquishedMcpServerMessage,
  unverifiedMcpServersMessage,
  userMcpServerKeptMessage,
} from "./mcp-ownership.js";

/**
 * A single activated artifact: the qualified ID resolved from input, plus the
 * bare shortname used for filesystem materialization (skill dir, MCP key, etc).
 */
interface Activation {
  qualified: QualifiedId;
  short: string;
}

/** Matches an env/header value that is exactly a single `${VAR}` reference. */
const WHOLE_VAR_RE = /^\$\{([^}]+)\}$/;

/** Matches a value that contains a `${VAR}` reference anywhere within it. */
const CONTAINS_VAR_RE = /\$\{[^}]+\}/;

/**
 * A plain POSIX environment-variable name. The `${...}` capture in
 * `WHOLE_VAR_RE` / `CONTAINS_VAR_RE` is deliberately permissive (`[^}]+`), so a
 * crafted value such as `${X:-$(cmd)}` would smuggle shell default-value /
 * command-substitution syntax through the `sh -c` rebind shim and the sub-shell
 * would EXECUTE it. Only names matching this pattern are ever routed into the
 * shim; anything else is treated as unforwardable (kept literal + warned), so
 * untrusted catalog config can never reach the shell as evaluatable syntax.
 */
const SAFE_ENV_NAME_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

export class CodexAdapter implements AgentAdapter {
  name = "codex";
  displayName = "OpenAI Codex";

  /**
   * Map AIR lifecycle event names to Codex `config.toml` hook event names.
   *
   * Accepts both snake_case AIR names and PascalCase Codex lifecycle names as
   * identity mappings, so hook authors targeting the Codex runtime can write
   * Codex-native event names directly without translating to snake_case.
   *
   * AIR events without a Codex equivalent (session_end, subagent_stop,
   * pre_compact, notification) are intentionally absent — `reconcileConfigHooks`
   * warns and skips registration when it encounters an unrecognized event.
   * Codex's PermissionRequest event has no AIR analog and is therefore not
   * generated by AIR (but user-authored PermissionRequest hooks are preserved).
   */
  private static readonly AIR_TO_CODEX_EVENT: Record<string, string> = {
    // snake_case AIR names
    session_start: "SessionStart",
    pre_tool_call: "PreToolUse",
    post_tool_call: "PostToolUse",
    user_prompt_submit: "UserPromptSubmit",
    stop: "Stop",
    // PascalCase Codex event names (identity — hook authors targeting Codex
    // often write these directly).
    SessionStart: "SessionStart",
    PreToolUse: "PreToolUse",
    PostToolUse: "PostToolUse",
    UserPromptSubmit: "UserPromptSubmit",
    Stop: "Stop",
    PermissionRequest: "PermissionRequest",
  };

  async isAvailable(): Promise<boolean> {
    try {
      execSync("which codex", { stdio: "pipe" });
      return true;
    } catch {
      return false;
    }
  }

  generateConfig(
    artifacts: ResolvedArtifacts,
    root?: RootEntry,
    _workDir?: string
  ): AgentSessionConfig {
    const pluginActivations = root?.default_plugins
      ? this.resolveActivations(artifacts.plugins, root.default_plugins, "plugin")
      : [];
    const plugins: Record<string, PluginEntry> = {};
    for (const a of pluginActivations) plugins[a.qualified] = artifacts.plugins[a.qualified];

    // Merge plugin-declared MCP servers and skills into root defaults (additive).
    // All incoming IDs are qualified (post-canonicalization at composition time),
    // so we deduplicate on qualified IDs.
    const mcpQualSet = new Set<string>(root?.default_mcp_servers ?? []);
    const skillQualSet = new Set<string>(root?.default_skills ?? []);
    for (const plugin of Object.values(plugins)) {
      if (plugin.mcp_servers) {
        for (const id of plugin.mcp_servers) mcpQualSet.add(id);
      }
      if (plugin.skills) {
        for (const id of plugin.skills) skillQualSet.add(id);
      }
    }

    const mcpActivations = this.resolveActivations(
      artifacts.mcp,
      [...mcpQualSet],
      "MCP server"
    );
    const skillActivations = this.resolveActivations(
      artifacts.skills,
      [...skillQualSet],
      "skill"
    );

    const mcpServers: Record<string, McpServerEntry> = {};
    for (const a of mcpActivations) mcpServers[a.short] = artifacts.mcp[a.qualified];
    const mcpConfig = this.translateMcpServersByShort(mcpServers);

    const pluginConfigs = pluginActivations.map((a) =>
      this.translatePlugin(a.short, artifacts.plugins[a.qualified])
    );

    const skillPaths = skillActivations.map((a) => artifacts.skills[a.qualified].path);

    return {
      agent: "codex",
      mcpConfig,
      pluginConfigs,
      skillPaths,
      env: {},
    };
  }

  buildStartCommand(config: AgentSessionConfig): StartCommand {
    // Codex auto-discovers `.codex/config.toml`, `.codex/hooks/`, and
    // `.agents/skills/` relative to its working root (trusted projects only).
    // Pointing the working root at the prepared directory loads everything;
    // no extra flags are required.
    return {
      command: "codex",
      args: [],
      env: config.env,
      cwd: config.workDir,
    };
  }

  /**
   * Prepare a working directory for an OpenAI Codex CLI session.
   *
   * Writes `.codex/config.toml` (MCP servers under `[mcp_servers.*]` and hook
   * registrations under `[hooks.*]`), injects skills + references into
   * `.agents/skills/<name>/`, copies path-based hooks into `.codex/hooks/<name>/`,
   * and returns the start command.
   *
   * Inputs to activation lists (root defaults, overrides, plugin-declared
   * primitives) are accepted as either qualified (`@scope/id`) or short form;
   * ambiguous short forms are rejected. Filesystem materialization uses
   * shortnames — Codex's `config.toml`, `.agents/skills/`, `.codex/hooks/`,
   * and the manifest are scope-naive. Two activated qualified IDs that share
   * a shortname hard-fail with a clear "add one to exclude" message.
   *
   * NOTE: `configFiles` is intentionally returned empty. Codex's config is
   * TOML, which is outside AIR's JSON-based transform/validation pipeline.
   * Secret references (`${VAR}`) in MCP env/headers are mapped to Codex-native
   * mechanisms at translation time: whole-value same-named refs to `env_vars`;
   * whole-value header refs to `env_http_headers`; renamed/partial env refs to a
   * `sh -c` shim that rebinds from forwarded source vars; and
   * `Authorization: Bearer ${VAR}` to `bearer_token_env_var`. Any `${VAR}` left
   * in the TOML is a *shell* expansion the sub-shell resolves — not an AIR
   * placeholder — so there is nothing for the pipeline to transform.
   */
  async prepareSession(
    artifacts: ResolvedArtifacts,
    targetDir: string,
    options?: PrepareSessionOptions
  ): Promise<PreparedSession> {
    const root = options?.root;
    const skillPaths: string[] = [];
    const hookPaths: string[] = [];

    // A manifest another adapter wrote names that adapter's directories, not
    // this one's: acting on it would claim or delete same-named entries here.
    const loadedManifest = loadManifest(targetDir);
    const prevManifest =
      loadedManifest?.adapter !== undefined && loadedManifest.adapter !== this.name
        ? null
        : loadedManifest;

    // 1. Resolve which artifacts to activate (overrides take precedence over root defaults)
    let mcpServerIds: string[] | undefined =
      options?.mcpServerOverrides ?? root?.default_mcp_servers ?? undefined;
    let skillIds: string[] = options?.skillOverrides ?? root?.default_skills ?? [];
    let hookIds: string[] = options?.hookOverrides ?? root?.default_hooks ?? [];

    // 1b. Merge subagent roots' artifacts if applicable.
    const subagentRoots = this.resolveSubagentRoots(root, artifacts, options);
    if (subagentRoots.length > 0) {
      const merged = this.mergeSubagentArtifacts(subagentRoots, mcpServerIds, skillIds);
      if (!options?.mcpServerOverrides) {
        mcpServerIds = merged.mcpServerIds;
      }
      if (!options?.skillOverrides) {
        skillIds = merged.skillIds;
      }
    }

    // 1c. Resolve plugins and merge their declared artifacts (additive)
    const pluginIds = options?.pluginOverrides ?? root?.default_plugins ?? undefined;
    const pluginActivations = pluginIds?.length
      ? this.resolveActivations(artifacts.plugins, pluginIds, "plugin")
      : [];
    const plugins: Record<string, PluginEntry> = {};
    for (const a of pluginActivations) plugins[a.qualified] = artifacts.plugins[a.qualified];

    const mcpSet = new Set<string>(mcpServerIds ?? []);
    const skillSet = new Set<string>(skillIds);
    const hookSet = new Set<string>(hookIds);
    for (const plugin of Object.values(plugins)) {
      if (plugin.mcp_servers) for (const id of plugin.mcp_servers) mcpSet.add(id);
      if (plugin.skills) for (const id of plugin.skills) skillSet.add(id);
      if (plugin.hooks) for (const id of plugin.hooks) hookSet.add(id);
    }
    if (mcpSet.size > 0 || mcpServerIds !== undefined) mcpServerIds = [...mcpSet];
    skillIds = [...skillSet];
    hookIds = [...hookSet];

    // 2. Resolve activations: qualified ID + shortname per artifact.
    //    Throws on unknown IDs, ambiguous shortnames, and shortname collisions.
    const skillActs = this.resolveActivations(artifacts.skills, skillIds, "skill");
    const mcpActs = mcpServerIds
      ? this.resolveActivations(artifacts.mcp, mcpServerIds, "MCP server")
      : [];
    const hookActs = this.resolveActivations(artifacts.hooks, hookIds, "hook");

    const skillShortIds = skillActs.map((a) => a.short);
    const hookShortIds = hookActs.map((a) => a.short);
    const mcpShortIds = mcpActs.map((a) => a.short);

    // 3. Reconcile against prior manifest using shortnames — those are the keys
    //    used for filesystem materialization and stored in the manifest.
    //    A version 1 manifest may claim skill directories AIR never created
    //    (#168), and a manifest before version 3 may claim MCP server keys AIR
    //    never wrote (#174); only the entries it can vouch for are carried
    //    forward.
    const skillsDir = join(targetDir, ".agents", "skills");
    const prevSkills = previousSkillOwnership(prevManifest, skillsDir, artifacts);
    for (const id of prevSkills.relinquished) {
      console.warn(relinquishedSkillMessage(`.agents/skills/${id}`));
    }
    const mcpConfigPath = join(targetDir, ".codex", "config.toml");
    const existingMcpServers = this.readMcpServers(mcpConfigPath);
    const prevMcpServers = previousMcpServerOwnership(
      prevManifest,
      existingMcpServers,
      artifacts,
      (short, server) => this.translateMcpServersByShort({ [short]: server })[short]
    );
    for (const id of prevMcpServers.relinquished) {
      console.warn(relinquishedMcpServerMessage(".codex/config.toml", id));
    }
    const ownedPrevManifest = prevManifest && {
      ...prevManifest,
      skills: [...prevSkills.owned],
      mcpServers: [...prevMcpServers.owned],
    };
    const diff = diffManifest(ownedPrevManifest, {
      skills: skillShortIds,
      hooks: hookShortIds,
      mcpServers: mcpShortIds,
    });

    for (const staleSkillId of diff.staleSkills) {
      const staleDir = join(targetDir, ".agents", "skills", staleSkillId);
      if (existsSync(staleDir)) {
        rmSync(staleDir, { recursive: true, force: true });
      }
    }

    for (const staleHookId of diff.staleHooks) {
      const staleDir = join(targetDir, ".codex", "hooks", staleHookId);
      if (existsSync(staleDir)) {
        rmSync(staleDir, { recursive: true, force: true });
      }
    }

    // 4. Inject skills + references into .agents/skills/<short>/
    const materializedSkillShortIds: string[] = [];
    for (const a of skillActs) {
      const skill = artifacts.skills[a.qualified];

      const skillTargetDir = join(targetDir, ".agents", "skills", a.short);

      if (existsSync(skillTargetDir)) {
        // Re-claim only a directory an earlier run created. One AIR didn't
        // create is the user's: leave it, and keep it out of the manifest so
        // no later run deletes it (#168).
        if (prevSkills.owned.has(a.short)) {
          materializedSkillShortIds.push(a.short);
        }
        continue;
      }

      const skillSourceDir = skill.path;
      if (!existsSync(skillSourceDir)) {
        console.warn(this.missingSourceDirMessage("skill", a.qualified, skillSourceDir));
        continue;
      }
      this.copyDirRecursive(skillSourceDir, skillTargetDir);
      skillPaths.push(skillTargetDir);
      materializedSkillShortIds.push(a.short);

      if (skill.references && skill.references.length > 0) {
        this.copyReferences(skill.references, skillTargetDir, artifacts);
      }
    }

    // 5. Validate and inject path-based hooks into .codex/hooks/<short>/.
    const prevHookIds = new Set(prevManifest?.hooks ?? []);
    const registeredHookShortIds: string[] = [];
    const registeredHookActivations: Array<{ short: string; qualified: string }> = [];
    for (const a of hookActs) {
      const hook = artifacts.hooks[a.qualified];

      const hookTargetDir = join(targetDir, ".codex", "hooks", a.short);
      const alreadyExists = existsSync(hookTargetDir);

      if (alreadyExists && !prevHookIds.has(a.short)) {
        continue;
      }

      if (!alreadyExists) {
        const hookSourceDir = hook.path;
        if (!existsSync(hookSourceDir)) {
          console.warn(this.missingSourceDirMessage("hook", a.qualified, hookSourceDir));
          continue;
        }
        this.copyDirRecursive(hookSourceDir, hookTargetDir);
        if (hook.references && hook.references.length > 0) {
          this.copyReferences(hook.references, hookTargetDir, artifacts);
        }
      }

      hookPaths.push(hookTargetDir);
      registeredHookShortIds.push(a.short);
      registeredHookActivations.push({ short: a.short, qualified: a.qualified });
    }

    // 6. Write `.codex/config.toml`: AIR-managed MCP servers and hook
    //    registrations, merged into any user-authored config (full replacement
    //    of AIR-owned keys; user keys preserved; stale AIR keys removed).
    //    A selected server is written only into a free key or over one AIR
    //    already owns. A key AIR didn't write is the user's: leave it, and keep
    //    it out of the manifest so no later run removes it (#174).
    const writtenMcpActs = mcpActs.filter((a) => {
      if (!hasMcpServer(existingMcpServers, a.short) || prevMcpServers.owned.has(a.short)) {
        return true;
      }
      if (!prevMcpServers.relinquished.includes(a.short)) {
        console.warn(userMcpServerKeptMessage(".codex/config.toml", a.short, a.qualified));
      }
      return false;
    });
    const translatedServers: Record<string, McpServerEntry> = {};
    for (const a of writtenMcpActs) translatedServers[a.short] = artifacts.mcp[a.qualified];

    const managedHookIds = new Set<string>([
      ...diff.staleHooks,
      ...registeredHookShortIds,
    ]);
    this.writeCodexConfig(
      targetDir,
      this.translateMcpServersByShort(translatedServers),
      diff.staleMcpServers,
      hookPaths,
      managedHookIds,
      this.collectOAuthCallbackUrl(translatedServers)
    );

    // 7. Persist the updated manifest (shortnames — keyed by filesystem dir).
    //    Only record skills/hooks/MCP servers actually written so the manifest
    //    does not claim ownership of artifacts AIR skipped (e.g. a missing source dir).
    writeManifest(
      buildManifest(targetDir, {
        adapter: this.name,
        skills: materializedSkillShortIds,
        hooks: registeredHookShortIds,
        mcpServers: writtenMcpActs.map((a) => a.short),
      })
    );

    // 8. Generate ephemeral subagent context for the session.
    //    Codex has no `--append-system-prompt` equivalent, so this is surfaced
    //    to the caller via `subagentContext` rather than the start command.
    let subagentContext: string | undefined;
    if (subagentRoots.length > 0) {
      subagentContext = this.buildSubagentContext(subagentRoots);
    }

    // 9. Build start command (working root = prepared directory).
    const config = this.generateConfig(artifacts, undefined, targetDir);
    const startCommand = this.buildStartCommand({
      ...config,
      workDir: targetDir,
    });

    return {
      // Empty by design — see method doc: Codex's TOML config is outside AIR's
      // JSON transform pipeline, and `${VAR}` references are mapped to
      // Codex-native mechanisms (env_vars / env_http_headers / a `sh -c` rebind
      // shim / bearer_token_env_var) at translation time, so there is nothing
      // for the pipeline to transform or validate. Any `${VAR}` remaining in the
      // TOML is a shell expansion, not an AIR placeholder. The
      // `.codex/config.toml` we wrote above is deliberately not surfaced.
      configFiles: [],
      skillPaths,
      hookPaths,
      hookActivations: registeredHookActivations,
      startCommand,
      subagentContext,
    };
  }

  /**
   * Enumerate skills checked into `<targetDir>/.agents/skills/`. Codex loads
   * these directly from the filesystem regardless of AIR's involvement, so
   * they're always active and must not be overwritten or removed. The TUI uses
   * this list to surface them as read-only entries.
   */
  async listLocalArtifacts(targetDir: string): Promise<LocalArtifacts> {
    return { skills: scanLocalSkills(targetDir) };
  }

  /**
   * Remove every artifact AIR has previously written into `targetDir`.
   *
   * Reads the per-target manifest, deletes each tracked skill / hook
   * directory, and removes tracked MCP server keys + AIR-managed hook entries
   * from `.codex/config.toml`. When every category is cleaned, the manifest
   * itself is deleted; partial cleans (any `keep*` flag set) update the
   * manifest with the kept entries so future runs continue to track them.
   *
   * Items in the manifest that no longer exist on disk are silently skipped
   * — the manifest can drift if a user removed files manually between runs.
   *
   * Skill entries in a version 1 manifest are the exception: that version
   * could claim a skill directory AIR never created (#168), so they are left
   * on disk and kept in the rewritten manifest instead of being removed.
   * MCP server entries in a manifest before version 3 are kept the same way,
   * since that version could claim a key the user wrote (#174).
   */
  async cleanSession(
    targetDir: string,
    options?: CleanSessionOptions
  ): Promise<CleanSessionResult> {
    const dryRun = options?.dryRun ?? false;
    const cleanSkills = !(options?.keepSkills ?? false);
    const cleanHooks = !(options?.keepHooks ?? false);
    const cleanMcpServers = !(options?.keepMcpServers ?? false);
    const fullClean = cleanSkills && cleanHooks && cleanMcpServers;

    const manifestPath = getManifestPath(targetDir);
    const manifestFileExists = existsSync(manifestPath);
    const manifest = loadManifest(targetDir);
    if (!manifest) {
      let corruptManifestRemoved = false;
      if (manifestFileExists && fullClean && !dryRun) {
        corruptManifestRemoved = deleteManifest(targetDir);
      }
      return {
        removedSkills: [],
        removedHooks: [],
        removedMcpServers: [],
        mcpConfigPath: null,
        settingsPath: null,
        manifestPath,
        manifestExisted: manifestFileExists,
        manifestRemoved: corruptManifestRemoved,
      };
    }

    const configPath = join(targetDir, ".codex", "config.toml");

    // A version 1 manifest may list skill directories AIR never created
    // (#168), and there is no catalog here to check them against, so they
    // stay on disk and in the manifest for the next prepareSession to check.
    const removedSkills: string[] = [];
    const unverifiedSkills: string[] = [];
    if (cleanSkills) {
      const skillsTrusted = manifestSkillsAreAirOwned(manifest);
      for (const id of manifest.skills) {
        const dir = join(targetDir, ".agents", "skills", id);
        if (!existsSync(dir)) continue;
        if (!skillsTrusted) {
          unverifiedSkills.push(id);
          continue;
        }
        if (!dryRun) rmSync(dir, { recursive: true, force: true });
        removedSkills.push(id);
      }
      if (unverifiedSkills.length > 0) {
        console.warn(
          unverifiedSkillsMessage(unverifiedSkills.map((id) => `.agents/skills/${id}`))
        );
      }
    }

    const removedHooks: string[] = [];
    if (cleanHooks) {
      for (const id of manifest.hooks) {
        const dir = join(targetDir, ".codex", "hooks", id);
        if (!existsSync(dir)) continue;
        if (!dryRun) rmSync(dir, { recursive: true, force: true });
        removedHooks.push(id);
      }
    }

    // Both MCP servers and hooks live in `.codex/config.toml`. Prune AIR-owned
    // entries in a single read/modify/write, preserving user-authored keys.
    // A manifest before version 3 may list MCP server keys AIR never wrote
    // (#174); with no catalog to check them against, they stay in place and
    // in the manifest for the next prepareSession to check.
    const mcpServersTrusted = manifestMcpServersAreAirOwned(manifest);
    const removedMcpServers: string[] = [];
    const unverifiedMcpServers: string[] = [];
    let mcpConfigPath: string | null = null;
    if ((cleanMcpServers && manifest.mcpServers.length > 0) ||
        (cleanHooks && manifest.hooks.length > 0)) {
      if (existsSync(configPath)) {
        const presentMcpIds = cleanMcpServers
          ? this.mcpServerIdsPresent(configPath, manifest.mcpServers)
          : [];
        const removableMcpIds = mcpServersTrusted ? presentMcpIds : [];
        if (!mcpServersTrusted) unverifiedMcpServers.push(...presentMcpIds);
        const willTouch =
          removableMcpIds.length > 0 || (cleanHooks && manifest.hooks.length > 0);
        if (willTouch) {
          if (!dryRun) {
            mcpConfigPath = this.pruneCodexConfig(
              configPath,
              removableMcpIds,
              cleanHooks ? new Set(manifest.hooks) : new Set(),
              cleanMcpServers && mcpServersTrusted
            );
          } else {
            mcpConfigPath = configPath;
          }
          for (const id of removableMcpIds) removedMcpServers.push(id);
        }
      }
    }
    if (unverifiedMcpServers.length > 0) {
      console.warn(unverifiedMcpServersMessage(".codex/config.toml", unverifiedMcpServers));
    }

    let manifestRemoved = false;
    if (fullClean && unverifiedSkills.length === 0 && unverifiedMcpServers.length === 0) {
      if (!dryRun) {
        manifestRemoved = deleteManifest(targetDir);
      } else {
        manifestRemoved = manifestFileExists;
      }
    } else if (!dryRun) {
      writeManifest({
        ...buildManifest(targetDir, {
          adapter: manifest.adapter ?? this.name,
          skills: cleanSkills ? unverifiedSkills : manifest.skills,
          hooks: cleanHooks ? [] : manifest.hooks,
          mcpServers: cleanMcpServers ? unverifiedMcpServers : manifest.mcpServers,
        }),
        // Clean only drops entries, so the version still describes what is
        // left — a version 1 manifest's skills, and an earlier manifest's MCP
        // servers, still need checking.
        version: manifest.version,
      });
    }

    return {
      removedSkills,
      removedHooks,
      removedMcpServers,
      // `.codex/config.toml` carries both MCP servers and hooks; report it as
      // the MCP config path. `settingsPath` stays null — Codex has no separate
      // settings file.
      mcpConfigPath,
      settingsPath: null,
      manifestPath,
      manifestExisted: true,
      manifestRemoved,
    };
  }

  /** The `[mcp_servers]` table in `.codex/config.toml`, or `{}` when absent or unparseable. */
  private readMcpServers(configPath: string): Record<string, unknown> {
    const servers = this.readToml(configPath).mcp_servers;
    return servers && typeof servers === "object" && !Array.isArray(servers)
      ? (servers as Record<string, unknown>)
      : {};
  }

  /**
   * Read `.codex/config.toml` and return the subset of `ids` whose key is
   * actually present under `[mcp_servers]`. Returns an empty list if the file
   * can't be parsed — we'd rather under-report than claim to have removed
   * entries we never touched.
   */
  private mcpServerIdsPresent(configPath: string, ids: string[]): string[] {
    const existing = this.readToml(configPath);
    const servers = (existing.mcp_servers as Record<string, unknown>) ?? {};
    return ids.filter((id) => Object.prototype.hasOwnProperty.call(servers, id));
  }

  /**
   * Resolve subagent roots from the root's default_subagent_roots.
   * IDs are already qualified after composition-time canonicalization.
   */
  private resolveSubagentRoots(
    root: RootEntry | undefined,
    artifacts: ResolvedArtifacts,
    options?: PrepareSessionOptions
  ): RootEntry[] {
    if (options?.skipSubagentMerge) return [];
    if (!root?.default_subagent_roots?.length) return [];

    const resolved: RootEntry[] = [];
    for (const id of root.default_subagent_roots) {
      const res = resolveReference(artifacts.roots, id, undefined);
      if (res.status === "ok") {
        resolved.push(artifacts.roots[res.qualified]);
      }
    }
    return resolved;
  }

  /**
   * Merge subagent roots' default_mcp_servers and default_skills into the
   * parent's activated sets (union, preserving order with parent first).
   */
  private mergeSubagentArtifacts(
    subagentRoots: RootEntry[],
    parentMcpServerIds: string[] | undefined,
    parentSkillIds: string[]
  ): { mcpServerIds: string[] | undefined; skillIds: string[] } {
    const mcpSet = new Set(parentMcpServerIds ?? []);
    const skillSet = new Set(parentSkillIds);

    for (const sub of subagentRoots) {
      if (sub.default_mcp_servers) {
        for (const id of sub.default_mcp_servers) mcpSet.add(id);
      }
      if (sub.default_skills) {
        for (const id of sub.default_skills) skillSet.add(id);
      }
    }

    return {
      mcpServerIds:
        parentMcpServerIds !== undefined || mcpSet.size > 0 ? [...mcpSet] : undefined,
      skillIds: [...skillSet],
    };
  }

  /**
   * Build a system prompt section describing the subagent root dependencies.
   */
  private buildSubagentContext(subagentRoots: RootEntry[]): string {
    const lines: string[] = [
      "## Subagent Root Dependencies",
      "",
      "This session includes capabilities from the following subagent roots.",
      "Their skills and MCP servers have been merged into your session.",
      "",
    ];

    for (const sub of subagentRoots) {
      lines.push(`### ${sub.display_name || "Subagent"}`);
      lines.push("");
      lines.push(`**Description**: ${sub.description}`);
      if (sub.default_mcp_servers?.length) {
        lines.push(`**MCP Servers**: ${sub.default_mcp_servers.join(", ")}`);
      }
      if (sub.default_skills?.length) {
        lines.push(`**Skills**: ${sub.default_skills.join(", ")}`);
      }
      if (sub.subdirectory) {
        lines.push(`**Subdirectory**: ${sub.subdirectory}`);
      }
      lines.push("");
    }

    return lines.join("\n");
  }

  /**
   * Translate a shortname-keyed MCP server map into Codex's `[mcp_servers.*]`
   * shape (as a plain object ready for TOML serialization). Callers convert
   * qualified IDs to shortnames before invoking this — Codex's config is
   * scope-naive.
   *
   * Secret handling is Codex-native and keeps secret *values* off disk — only
   * variable *names* are ever written to `config.toml`. Three env shapes:
   *
   *   - `KEY = "${KEY}"` (whole-value, same name) → `env_vars = ["KEY"]`
   *     (Codex injects the host's `KEY` at launch).
   *   - `KEY = "${OTHER}"` (whole-value, renamed) or `KEY = "Bearer ${TOKEN}"`
   *     (partial) → Codex's `env_vars` can express neither, so the launch is
   *     wrapped in a `sh -c` shim that rebinds `KEY` from the forwarded source
   *     var(s) right before `exec` hands off to the real MCP binary. The source
   *     var(s) are forwarded via `env_vars`; the value is templated as a shell
   *     double-quoted string so the sub-shell expands it.
   *   - `KEY = "literal"` (no ref) → `[mcp_servers.<name>.env]` table.
   *
   * For remote servers, a *whole-value* header ref (`${VAR}`, renamed or not)
   * becomes an `env_http_headers` entry (Codex maps header → host var). An
   * `Authorization: "Bearer ${VAR}"` value maps to Codex's native
   * `bearer_token_env_var`. Any other *partial* header value has no Codex
   * expression — remote servers have no launch process to wrap — so it stays
   * literal in `http_headers` and warns (`warnUnforwardableSecret`).
   */
  translateMcpServersByShort(
    servers: Record<string, McpServerEntry>
  ): Record<string, Record<string, unknown>> {
    const out: Record<string, Record<string, unknown>> = {};
    for (const [name, server] of Object.entries(servers)) {
      out[name] = this.translateMcpServer(name, server);
    }
    return out;
  }

  private translateMcpServer(name: string, server: McpServerEntry): Record<string, unknown> {
    if (server.type === "stdio") {
      const envTable: Record<string, string> = {};
      const envVars: string[] = [];
      const rebindings: string[] = [];
      const forward = (v: string) => {
        if (!envVars.includes(v)) envVars.push(v);
      };

      for (const [key, value] of Object.entries(server.env ?? {})) {
        const m = WHOLE_VAR_RE.exec(value);
        if (m && m[1] === key) {
          // `${KEY}` referencing the host var of the same name → forward it.
          forward(key);
        } else if (CONTAINS_VAR_RE.test(value)) {
          // Renamed whole-value (`KEY = "${OTHER}"`) or partial
          // (`"Bearer ${TOKEN}"`) ref. Codex's env_vars can express neither, so
          // rebind `key` inside a `sh -c` shim from the forwarded source var(s).
          //
          // Guard the shim against shell injection: it interpolates `key` on the
          // assignment's left-hand side (`KEY=...`) and each `${VAR}` reference
          // on the right. A key with shell metacharacters (`A;rm -rf /`) or a
          // reference carrying shell syntax (`${X:-$(cmd)}`) would be EXECUTED by
          // the sub-shell. Only forward when the key and every reference are
          // plain POSIX variable names; otherwise keep the value literal + warn.
          if (SAFE_ENV_NAME_RE.test(key) && this.allVarRefsSafe(value)) {
            const { quoted, vars } = this.toShellDoubleQuoted(value);
            rebindings.push(`${key}=${quoted}`);
            for (const v of vars) forward(v);
          } else {
            this.warnUnsafeEnvReference(name, key, value);
            envTable[key] = value;
          }
        } else {
          // Literal value → plain env table.
          envTable[key] = value;
        }
      }

      const out: Record<string, unknown> = {};
      if (rebindings.length > 0 && server.command) {
        // Wrap the real launch so the rebindings apply in the sub-shell right
        // before `exec` replaces it with the MCP binary. Forwarded source vars
        // arrive via env_vars and literal entries via the env table; both
        // survive `exec` into the real process. The original command/args are
        // single-quoted so the shell treats them as literal words.
        const original = [server.command, ...(server.args ?? [])]
          .map((part) => this.shSingleQuote(part))
          .join(" ");
        out.command = "sh";
        out.args = ["-c", `${rebindings.join(" ")} exec ${original}`];
      } else {
        // No command to wrap (malformed stdio entry — `command` is required by
        // schema): skip the shim entirely so we never emit `exec ''`. The
        // renamed/partial refs that produced `rebindings` are dropped here, but a
        // command-less stdio server can't launch anyway.
        if (rebindings.length > 0) this.warnRebindWithoutCommand(name, rebindings);
        out.command = server.command;
        if (server.args && server.args.length > 0) out.args = server.args;
      }
      if (envVars.length > 0) out.env_vars = envVars;
      if (Object.keys(envTable).length > 0) out.env = envTable;
      return out;
    }

    // Remote server (sse or streamable-http). Codex models both as a URL-based
    // streamable HTTP server and auto-detects the transport from the URL.
    const out: Record<string, unknown> = { url: server.url };
    const httpHeaders: Record<string, string> = {};
    const envHttpHeaders: Record<string, string> = {};
    let bearerTokenEnvVar: string | undefined;
    for (const [key, value] of Object.entries(server.headers ?? {})) {
      const m = WHOLE_VAR_RE.exec(value);
      if (m) {
        // Whole-value ref (renamed or not): env_http_headers maps a header name
        // to a host var of any name, so renames forward cleanly here.
        envHttpHeaders[key] = m[1];
      } else if (CONTAINS_VAR_RE.test(value)) {
        const bearer = /^Bearer\s+\$\{([^}]+)\}$/.exec(value);
        if (key.toLowerCase() === "authorization" && bearer) {
          // `Authorization: Bearer ${VAR}` → Codex's native bearer-token
          // forwarding. Codex emits the Authorization header itself, so the
          // header is not also written to http_headers.
          bearerTokenEnvVar = bearer[1];
        } else {
          // A non-Bearer partial header has no Codex-native expression (remote
          // servers have no launch process to wrap in a shell shim), so it
          // stays literal and warns.
          this.warnUnforwardableSecret(name, `headers["${key}"]`, value);
          httpHeaders[key] = value;
        }
      } else {
        httpHeaders[key] = value;
      }
    }
    if (Object.keys(httpHeaders).length > 0) out.http_headers = httpHeaders;
    if (Object.keys(envHttpHeaders).length > 0) out.env_http_headers = envHttpHeaders;
    if (bearerTokenEnvVar) out.bearer_token_env_var = bearerTokenEnvVar;
    // AIR's OAuth client_id maps to Codex's per-server `[mcp_servers.<id>.oauth]`
    // table; emitting an explicit client_id bypasses OAuth dynamic client
    // registration (RFC 7591), which some providers reject. The redirect URI is
    // global in Codex — see `collectOAuthCallbackUrl` / `mcp_oauth_callback_url`.
    if (server.oauth?.clientId) {
      out.oauth = { client_id: server.oauth.clientId };
    }
    // Codex's per-server oauth table accepts only `client_id` (and the global
    // callback URL); it has no slot for scopes, a confidential client secret, or
    // an explicit auth-server metadata URL. Warn rather than silently dropping
    // these so an author relying on them isn't left with a quietly broken flow.
    if (server.oauth) {
      const unmappable: string[] = [];
      if (server.oauth.scopes && server.oauth.scopes.length > 0) unmappable.push("scopes");
      if (server.oauth.clientSecret) unmappable.push("clientSecret");
      if (server.oauth.authServerMetadataUrl) unmappable.push("authServerMetadataUrl");
      if (unmappable.length > 0) this.warnUnmappableOAuthFields(name, unmappable);
    }
    return out;
  }

  /** POSIX single-quote a string so a shell treats it as one literal word. */
  private shSingleQuote(value: string): string {
    return `'${value.replace(/'/g, `'\\''`)}'`;
  }

  /**
   * Whether every `${...}` reference in `value` is a plain POSIX variable name.
   * The capture used elsewhere is permissive (`[^}]+`), so this gates which
   * values may enter the `sh -c` rebind shim — a reference like `${X:-$(cmd)}`
   * carries shell syntax the sub-shell would execute and must be rejected.
   */
  private allVarRefsSafe(value: string): boolean {
    const re = /\$\{([^}]+)\}/g;
    let m: RegExpExecArray | null;
    while ((m = re.exec(value)) !== null) {
      if (!SAFE_ENV_NAME_RE.test(m[1])) return false;
    }
    return true;
  }

  /**
   * Render an AIR value containing `${VAR}` refs as a shell double-quoted
   * string: literal runs are escaped for the double-quote context and each
   * `${VAR}` is preserved so the sub-shell expands it from the forwarded host
   * env. Returns the quoted string and the de-duplicated source var names so the
   * caller can forward them via `env_vars`.
   */
  private toShellDoubleQuoted(value: string): { quoted: string; vars: string[] } {
    const vars: string[] = [];
    const re = /\$\{([^}]+)\}/g;
    let body = "";
    let last = 0;
    let m: RegExpExecArray | null;
    while ((m = re.exec(value)) !== null) {
      body += this.escapeShellDoubleQuoted(value.slice(last, m.index));
      body += `\${${m[1]}}`;
      if (!vars.includes(m[1])) vars.push(m[1]);
      last = m.index + m[0].length;
    }
    body += this.escapeShellDoubleQuoted(value.slice(last));
    return { quoted: `"${body}"`, vars };
  }

  /** Escape characters that are special inside a double-quoted shell string. */
  private escapeShellDoubleQuoted(text: string): string {
    return text.replace(/[\\"`$]/g, "\\$&");
  }

  /**
   * Collect the single OAuth callback URL Codex can honor across all OAuth-using
   * MCP servers. Codex exposes only one top-level `mcp_oauth_callback_url`, so if
   * servers declare distinct `redirectUri`s we keep the first and warn that the
   * rest are dropped. Returns undefined when no server declares one.
   */
  private collectOAuthCallbackUrl(
    servers: Record<string, McpServerEntry>
  ): string | undefined {
    const urls: string[] = [];
    for (const server of Object.values(servers)) {
      const uri = server.oauth?.redirectUri;
      if (uri && !urls.includes(uri)) urls.push(uri);
    }
    if (urls.length === 0) return undefined;
    if (urls.length > 1) {
      console.warn(
        `[air-adapter-codex] Multiple MCP servers declare distinct OAuth redirect ` +
          `URIs (${urls.join(", ")}), but Codex honors only a single top-level ` +
          `mcp_oauth_callback_url. Using "${urls[0]}" and ignoring the rest.`
      );
    }
    return urls[0];
  }

  /**
   * Warn that a stdio `env` value can't be safely rebound via the `sh -c` shim:
   * the env *name* or a `${VAR}` reference inside the value is not a plain POSIX
   * variable name, so it carries shell syntax (e.g. `${X:-$(cmd)}`) the sub-shell
   * would execute. The value is kept literal in the `env` table (Codex injects it
   * verbatim) rather than shipping an injectable shim. Rewrite it using plain
   * variable references (e.g. `KEY = "${OTHER}"`).
   */
  private warnUnsafeEnvReference(serverName: string, key: string, value: string): void {
    console.warn(
      `[air-adapter-codex] MCP server "${serverName}" env["${key}"] = "${value}" ` +
        `cannot be forwarded: the env name or a \${VAR} reference is not a plain ` +
        `variable name ([A-Za-z_][A-Za-z0-9_]*), so routing it through the launch ` +
        `shim could let the shell evaluate embedded syntax. The value is written to ` +
        `.codex/config.toml verbatim and Codex will inject the literal "\${…}" string ` +
        `at runtime. Rewrite it using plain variable references (e.g. KEY = "\${OTHER}").`
    );
  }

  /**
   * Warn that a stdio server declared renamed/partial env refs (which need a
   * `sh -c` rebind shim) but has no `command` to wrap, so the shim was skipped
   * to avoid emitting `exec ''`. A command-less stdio server is malformed
   * (`command` is required by schema) and can't launch regardless.
   */
  private warnRebindWithoutCommand(serverName: string, rebindings: string[]): void {
    console.warn(
      `[air-adapter-codex] MCP server "${serverName}" has env references needing a ` +
        `launch shim (${rebindings.join(", ")}) but no command to wrap. The shim was ` +
        `skipped; set a command so the references can be rebound at launch.`
    );
  }

  /**
   * Warn that OAuth fields with no Codex per-server config slot were dropped.
   * Codex's `[mcp_servers.<id>.oauth]` table accepts only `client_id` (plus the
   * global `mcp_oauth_callback_url`), so `scopes`, `clientSecret`, and
   * `authServerMetadataUrl` cannot be expressed. Surface them rather than letting
   * an author's auth flow break silently.
   */
  private warnUnmappableOAuthFields(serverName: string, fields: string[]): void {
    console.warn(
      `[air-adapter-codex] MCP server "${serverName}" oauth.${fields.join(", oauth.")} ` +
        `${fields.length === 1 ? "has" : "have"} no Codex equivalent and ` +
        `${fields.length === 1 ? "was" : "were"} dropped. Codex's per-server oauth ` +
        `config accepts only client_id (and the global mcp_oauth_callback_url). If ` +
        `the provider requires these, configure them in Codex directly.`
    );
  }

  /**
   * Warn that a *partial* header value embeds a `${VAR}` reference Codex can't
   * express. Whole-value header refs forward via `env_http_headers`, and an
   * `Authorization: Bearer ${VAR}` value maps to `bearer_token_env_var`. Any
   * other partial header value (e.g. `X-Key = "v1-${TOKEN}"`) has no Codex
   * equivalent — remote servers have no launch process to wrap in a shell shim —
   * so it is written to `.codex/config.toml` literally and Codex injects the
   * literal `${…}` string at runtime. (Stdio `env` refs never reach here:
   * renamed/partial env values are rebound via a `sh -c` shim instead.)
   */
  private warnUnforwardableSecret(serverName: string, field: string, value: string): void {
    console.warn(
      `[air-adapter-codex] MCP server "${serverName}" ${field} = "${value}" embeds a ` +
        `\${VAR} reference inside a larger header value that Codex cannot express. ` +
        `env_http_headers forwards only whole-value header refs, and bearer_token_env_var ` +
        `covers only "Authorization: Bearer \${VAR}", so this value is written to ` +
        `.codex/config.toml verbatim and Codex will inject the literal "\${…}" string at ` +
        `runtime. Rewrite it as a whole-value ref (e.g. Authorization = "\${API_TOKEN}") or ` +
        `set the value directly.`
    );
  }

  /**
   * Translate an AIR plugin to a Codex-facing descriptor.
   *
   * Codex's marketplace plugins are remote-installed (`codex plugin add`) and
   * have no local package file an adapter can materialize. AIR therefore treats
   * plugins as composition sugar: a plugin's declared MCP servers / skills /
   * hooks are expanded into the activation set and materialized as their
   * underlying Codex-native artifacts. This descriptor is informational only.
   */
  translatePlugin(shortId: string, plugin: PluginEntry): Record<string, unknown> {
    return {
      name: shortId,
      description: plugin.description,
      ...(plugin.version && { version: plugin.version }),
    };
  }

  /**
   * Resolve a list of activation IDs (each qualified or short) into qualified
   * IDs paired with shortnames suitable for filesystem materialization.
   *
   * Throws on:
   *   - unknown IDs (after attempting both qualified and short-form lookup)
   *   - ambiguous short references (multiple scopes contribute the shortname)
   *   - shortname collisions in the activation set itself (two qualified IDs
   *     with the same shortname can't share a single materialization dir)
   */
  private resolveActivations<T>(
    pool: Record<string, T>,
    ids: string[],
    artifactType: string
  ): Activation[] {
    const acts: Activation[] = [];
    const errors: string[] = [];
    const shortToQualified = new Map<string, string>();

    for (const id of ids) {
      const res = resolveReference(pool, id, undefined);
      if (res.status === "missing") {
        errors.push(
          `Unknown ${artifactType} ID "${id}". Available: ${this.formatPoolKeys(pool)}.`
        );
        continue;
      }
      if (res.status === "ambiguous") {
        errors.push(
          `${artifactType} reference "${id}" is ambiguous — candidates: ` +
            `${res.candidates.join(", ")}. Use the qualified form to disambiguate.`
        );
        continue;
      }
      const qualified = res.qualified;
      const { id: short } = parseQualifiedId(qualified);
      const prior = shortToQualified.get(short);
      if (prior !== undefined && prior !== qualified) {
        errors.push(
          `${artifactType} shortname collision: both "${prior}" and "${qualified}" ` +
            `are activated and would write to the same target name "${short}". ` +
            `Add one to air.json#exclude or activate only one of them.`
        );
        continue;
      }
      if (prior === qualified) continue; // dedup
      shortToQualified.set(short, qualified);
      acts.push({ qualified, short });
    }

    if (errors.length > 0) {
      throw new Error(
        errors.length === 1 ? errors[0] : `Activation errors:\n  - ${errors.join("\n  - ")}`
      );
    }
    return acts;
  }

  /**
   * Build the warning emitted when a registered artifact's `path` does not
   * exist on disk at materialization time. The qualified ID encodes the
   * declaring catalog's scope, so a reviewer can trace the offending entry
   * back to its index file. Materialization is skipped for this artifact and
   * the rest of the session proceeds.
   */
  private missingSourceDirMessage(
    artifactType: "skill" | "hook",
    qualified: string,
    resolvedPath: string
  ): string {
    return (
      `warning: ${artifactType} "${qualified}" declares path "${resolvedPath}" but that directory does not exist — skipping. ` +
      `The catalog that contributed "${qualified}" registered a path AIR cannot materialize. ` +
      `Fix the \`path\` field in the catalog's index file (or exclude the artifact in air.json) to restore the ${artifactType}.`
    );
  }

  private formatPoolKeys<T>(pool: Record<string, T>): string {
    const keys = Object.keys(pool);
    if (keys.length === 0) return "(none)";
    if (keys.length > 8) {
      return `${keys.slice(0, 8).join(", ")}, … (${keys.length} total)`;
    }
    return keys.join(", ");
  }

  /**
   * Copy referenced documents into a references/ subdirectory of the target.
   * `refIds` are qualified IDs (post-canonicalization).
   */
  private copyReferences(
    refIds: string[],
    targetDir: string,
    artifacts: ResolvedArtifacts
  ): void {
    const refsTargetDir = join(targetDir, "references");
    for (const refId of refIds) {
      const ref = artifacts.references[refId];
      if (!ref) continue;
      const refSourcePath = ref.path;
      if (existsSync(refSourcePath)) {
        const refTargetPath = join(
          refsTargetDir,
          ref.path.split("/").pop() || ref.path
        );
        mkdirSync(dirname(refTargetPath), { recursive: true });
        copyFileSync(refSourcePath, refTargetPath);
      }
    }
  }

  // ============================================================
  // `.codex/config.toml` read / merge / write
  // ============================================================

  /** Parse an existing `config.toml`, returning `{}` when absent/unparseable. */
  private readToml(path: string): Record<string, unknown> {
    if (!existsSync(path)) return {};
    try {
      return parseToml(readFileSync(path, "utf-8")) as Record<string, unknown>;
    } catch {
      return {};
    }
  }

  /**
   * Merge AIR-managed MCP servers and hook registrations into
   * `.codex/config.toml`, preserving any user-authored config.
   *
   * - MCP: keys in `staleMcpIds` are removed; keys in `translatedServers`
   *   are set/replaced; other servers and top-level keys pass through.
   * - OAuth callback URL: the single top-level `mcp_oauth_callback_url` is an
   *   AIR-managed derived key — set when an OAuth-using server declares a
   *   `redirectUri`, removed otherwise (recomputed every run).
   * - Hooks: AIR-owned entries (tagged with `_air_hook_id`) whose ID is in
   *   `managedHookIds` are pruned, then the current selection is registered.
   *
   * Returns the path written.
   */
  private writeCodexConfig(
    targetDir: string,
    translatedServers: Record<string, Record<string, unknown>>,
    staleMcpIds: string[],
    newHookPaths: string[],
    managedHookIds: Set<string>,
    oauthCallbackUrl?: string
  ): string {
    const configPath = join(targetDir, ".codex", "config.toml");
    const config = this.readToml(configPath);

    // --- MCP servers ---
    const servers = (config.mcp_servers as Record<string, unknown>) ?? {};
    for (const id of staleMcpIds) delete servers[id];
    for (const [id, cfg] of Object.entries(translatedServers)) servers[id] = cfg;
    if (Object.keys(servers).length > 0) {
      config.mcp_servers = servers;
    } else {
      delete config.mcp_servers;
    }

    // --- Global MCP OAuth callback URL (single top-level key) ---
    // Treated as an AIR-managed derived key: set when present, removed when AIR
    // no longer manages an OAuth server with a redirectUri.
    if (oauthCallbackUrl !== undefined) {
      config.mcp_oauth_callback_url = oauthCallbackUrl;
    } else {
      delete config.mcp_oauth_callback_url;
    }

    // --- Hooks ---
    this.reconcileConfigHooks(config, targetDir, newHookPaths, managedHookIds);

    // Nothing to persist: don't leave an empty `.codex/config.toml` behind, and
    // remove a now-empty one if a prior run (or user edit) emptied it out.
    if (Object.keys(config).length === 0) {
      if (existsSync(configPath)) rmSync(configPath, { force: true });
      return configPath;
    }

    mkdirSync(dirname(configPath), { recursive: true });
    writeFileSync(configPath, stringifyToml(config) + "\n");
    return configPath;
  }

  /**
   * Reconcile the `[hooks.*]` tables on the in-memory config object.
   *
   * Codex represents hooks as `hooks.<Event> = [ { matcher, hooks: [ {type,
   * command, timeout?, statusMessage?} ] } ]`. AIR-owned matcher groups are
   * identified by an `_air_hook_id` marker on the inner hook entry (Codex
   * ignores unrecognized keys unless `--strict-config` is set). Groups whose ID
   * is in `managedHookIds` are removed, then the current `newHookPaths` are
   * registered for their mapped events.
   */
  private reconcileConfigHooks(
    config: Record<string, unknown>,
    targetDir: string,
    newHookPaths: string[],
    managedHookIds: Set<string>
  ): void {
    const hooks = (config.hooks as Record<string, unknown[]>) ?? {};

    for (const event of Object.keys(hooks)) {
      const matcherGroups = hooks[event];
      if (!Array.isArray(matcherGroups)) continue;
      const prunedGroups: unknown[] = [];
      for (const group of matcherGroups) {
        if (!group || typeof group !== "object") {
          prunedGroups.push(group);
          continue;
        }
        const g = group as Record<string, unknown>;
        const inner = Array.isArray(g.hooks) ? (g.hooks as unknown[]) : [];
        const keptInner = inner.filter(
          (h) => !this.isManagedHookEntry(h, managedHookIds)
        );
        if (keptInner.length === 0) continue;
        prunedGroups.push({ ...g, hooks: keptInner });
      }
      if (prunedGroups.length === 0) {
        delete hooks[event];
      } else {
        hooks[event] = prunedGroups;
      }
    }

    for (const hookPath of newHookPaths) {
      const hookJsonPath = join(hookPath, "HOOK.json");
      if (!existsSync(hookJsonPath)) continue;

      let hookJson: Record<string, unknown>;
      try {
        hookJson = JSON.parse(readFileSync(hookJsonPath, "utf-8"));
      } catch {
        continue;
      }
      const hookId = hookPath.split(/[\\/]/).filter(Boolean).pop() || "";
      const rawEvent = hookJson.event;
      const codexEvent =
        typeof rawEvent === "string"
          ? CodexAdapter.AIR_TO_CODEX_EVENT[rawEvent]
          : undefined;
      if (!codexEvent) {
        if (rawEvent !== undefined) {
          console.warn(
            `warning: hook "${hookId}" declares unrecognized event "${String(
              rawEvent
            )}" — skipping registration in .codex/config.toml. ` +
              `Supported events: ${this.supportedEventList()}.`
          );
        }
        continue;
      }
      if (!hookJson.command) continue;

      const hookRelDir = relative(targetDir, hookPath);
      const command = this.buildHookCommand(
        hookRelDir,
        hookPath,
        hookJson.command as string,
        hookJson.args as string[] | undefined
      );

      const hookEntry: Record<string, unknown> = {
        type: "command",
        command,
        _air_hook_id: hookId,
      };
      if (hookJson.timeout_seconds != null) {
        hookEntry.timeout = hookJson.timeout_seconds;
      }

      const matcherGroup: Record<string, unknown> = {
        matcher: hookJson.matcher ?? "",
        hooks: [hookEntry],
      };

      if (!hooks[codexEvent]) {
        hooks[codexEvent] = [];
      }
      (hooks[codexEvent] as unknown[]).push(matcherGroup);
    }

    if (Object.keys(hooks).length > 0) {
      config.hooks = hooks;
    } else {
      delete config.hooks;
    }
  }

  private isManagedHookEntry(entry: unknown, managedHookIds: Set<string>): boolean {
    if (!entry || typeof entry !== "object") return false;
    const id = (entry as Record<string, unknown>)._air_hook_id;
    if (typeof id !== "string") return false;
    return managedHookIds.has(id);
  }

  /**
   * Remove `mcpIds` from `[mcp_servers]` and AIR-managed hook entries (matched
   * by `_air_hook_id` ∈ `managedHookIds`) from `[hooks.*]` in
   * `.codex/config.toml`, preserving user-authored entries and other top-level
   * fields. When `removeOAuthCallbackUrl` is set (MCP servers are being
   * cleaned), the AIR-managed `mcp_oauth_callback_url` key is dropped too.
   * Returns the path of the file that was rewritten, or null if the file became
   * empty and was deleted.
   */
  private pruneCodexConfig(
    configPath: string,
    mcpIds: string[],
    managedHookIds: Set<string>,
    removeOAuthCallbackUrl = false
  ): string | null {
    const config = this.readToml(configPath);

    const servers = (config.mcp_servers as Record<string, unknown>) ?? {};
    for (const id of mcpIds) delete servers[id];
    if (Object.keys(servers).length > 0) {
      config.mcp_servers = servers;
    } else {
      delete config.mcp_servers;
    }

    if (removeOAuthCallbackUrl) delete config.mcp_oauth_callback_url;

    if (managedHookIds.size > 0) {
      this.reconcileConfigHooks(config, dirname(dirname(configPath)), [], managedHookIds);
    }

    if (Object.keys(config).length === 0) {
      rmSync(configPath, { force: true });
      return null;
    }

    writeFileSync(configPath, stringifyToml(config) + "\n");
    return configPath;
  }

  /**
   * Build a shell command string from HOOK.json's command and args fields.
   *
   * Hook authors write paths relative to their own hook directory. Codex
   * invokes hooks with a working directory that is not guaranteed to be the
   * project root, so hook-relative paths are anchored to the repository root
   * via `"$(git rev-parse --show-toplevel)/.codex/hooks/<id>/<path>"` — the
   * idiom used in Codex's own hook documentation. The double quotes keep the
   * path safe for project directories with spaces.
   *
   *   - `command` is anchored if it starts with `./` (explicit hook-relative).
   *   - Each `args` entry is anchored if it looks like a path AND the file
   *     exists under the hook's installed directory.
   *
   * Args that are not rewritten and contain shell metacharacters are
   * single-quoted for safety.
   */
  private buildHookCommand(
    hookRelDir: string,
    hookAbsDir: string,
    command: string,
    args?: string[]
  ): string {
    let cmd: string;
    if (command.startsWith("./")) {
      cmd = this.anchorHookPath(join(hookRelDir, command.slice(2)));
    } else {
      cmd = command;
    }
    if (args && args.length > 0) {
      const rewritten = args.map((a) =>
        this.rewriteHookArgPath(a, hookRelDir, hookAbsDir)
      );
      const escaped = rewritten.map((r) =>
        r.anchored
          ? this.anchorHookPath(r.value)
          : /[\s;&|`$"'\\]/.test(r.value)
            ? `'${r.value.replace(/'/g, "'\\''")}'`
            : r.value
      );
      cmd += " " + escaped.join(" ");
    }
    return cmd;
  }

  /**
   * Wrap a project-root-relative path in `"$(git rev-parse --show-toplevel)/..."`
   * so the resolved path is independent of the cwd at hook invocation. Double
   * quotes are required so the command substitution runs; characters that are
   * special inside double quotes (`$`, `` ` ``, `"`, `\`) are escaped in the
   * path component so an unusual hook ID or filename can't break out of the
   * quoting.
   */
  private anchorHookPath(projectRelPath: string): string {
    const safe = projectRelPath.replace(/[\\"$`]/g, "\\$&");
    return `"$(git rev-parse --show-toplevel)/${safe}"`;
  }

  /**
   * If `arg` is a hook-relative path that points at a real file under the
   * hook's installed directory, return its project-root-relative form
   * (`.codex/hooks/<id>/<path>`) flagged as anchored so the caller can wrap it.
   * Otherwise return `arg` unchanged with `anchored: false`.
   */
  private rewriteHookArgPath(
    arg: string,
    hookRelDir: string,
    hookAbsDir: string
  ): { value: string; anchored: boolean } {
    if (!arg) return { value: arg, anchored: false };
    if (arg.startsWith("-") || arg.startsWith("/") || arg.startsWith("~")) {
      return { value: arg, anchored: false };
    }
    const hasExplicitPrefix = arg.startsWith("./");
    const candidate = hasExplicitPrefix ? arg.slice(2) : arg;
    if (!hasExplicitPrefix && !candidate.includes("/")) {
      return { value: arg, anchored: false };
    }
    if (!existsSync(join(hookAbsDir, candidate))) {
      return { value: arg, anchored: false };
    }
    return { value: join(hookRelDir, candidate), anchored: true };
  }

  /** Human-readable list of the supported AIR hook event names (snake_case only). */
  private supportedEventList(): string {
    const seen = new Set<string>();
    const names: string[] = [];
    for (const [key, value] of Object.entries(CodexAdapter.AIR_TO_CODEX_EVENT)) {
      if (key === value) continue; // skip PascalCase identity entries
      if (seen.has(key)) continue;
      seen.add(key);
      names.push(key);
    }
    return names.join(", ");
  }

  private copyDirRecursive(src: string, dest: string): void {
    mkdirSync(dest, { recursive: true });
    for (const entry of readdirSync(src)) {
      const srcPath = join(src, entry);
      const destPath = join(dest, entry);
      if (statSync(srcPath).isDirectory()) {
        this.copyDirRecursive(srcPath, destPath);
      } else {
        copyFileSync(srcPath, destPath);
      }
    }
  }
}
